Repository frintjs/frint, pull requests merged in 2018-07, with the labels that each got.

#427 frint-react: add `hydrate` function to `frint-react`
  packages/frint-react/README.md
  packages/frint-react/src/hydrate.js
  packages/frint-react/src/hydrate.spec.js
  packages/frint-react/src/index.js
  packages/frint-react/src/index.spec.js
Labels: PR, feature, minor

#429 Added support for SSR on regions and refactored to remove handlers
  packages/frint-react-server/src/renderToString.spec.js
  packages/frint-react/package.json
  packages/frint-react/src/components/Region.js
  packages/frint-react/src/components/Region.spec.js
  packages/frint-react/src/handlers/ReactHandler.spec.js
Labels: PR, patch

#430 Region component added render prop support
  packages/frint-react/README.md
  packages/frint-react/src/components/Region.js
  packages/frint-react/src/components/Region.spec.js
Labels: PR, minor

#431 frint: Expose class methods on the app instance level
  packages/frint/README.md
  packages/frint/src/App.spec.ts
  packages/frint/src/App.ts
Labels: PR, feature, minor

#434 frint-react: Fix typo in `children` prop type
  packages/frint-react/src/components/Region.js
Labels: PR, bug, minor
